version: '3'

services:
  nextcloud:
    image: nextcloud:apache
    restart: always
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - ./data/nextcloud:/var/www/html
    environment:
      MYSQL_HOST: '${DB_HOST}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_DATABASE: '${DB_DATABASE}'

      REDIS_HOST: '${REDIS_HOST}'
    networks:
      - nginx-pm_default
      - nextcloud
    depends_on:
      - mysql
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html
    networks:
      - nginx-pm_default
      - nextcloud
    entrypoint: /cron.sh
    depends_on:
      - mysql
      - redis

  mysql:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    networks:
      - nextcloud

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - nextcloud

networks:
  nginx-pm_default:
    external:
      name: nginx-pm_default
  nextcloud:
    driver: bridge