version: '3.7'
services:
  nextcloud:
    container_name: 'nextcloud_app'
    image: nextcloud:apache
    restart: always
#    ports:
#      - '${APP_PORT:-80}:80'
    volumes:
      - ./data/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}

      - REDIS_HOST=${REDIS_HOST}
    networks:
      - nginx_pm
      - backend
      - nextcloud
    healthcheck:
      test: curl --fail -s http://localhost:80/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - cron
  cron:
    container_name: 'nextcloud_cron'
    image: nextcloud:apache
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html
    networks:
      - backend
      - nextcloud
    entrypoint: /cron.sh
networks:
  nginx_pm:
    external:
      name: nginx_pm_network
  backend:
    external:
      name: backend_network
  nextcloud:
    name: nextcloud_network

